# Generated by Django 2.2.3 on 2019-07-03 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grid5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('grid', models.IntegerField()),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
            options={
                'ordering': ['lake__abbrev', 'grid'],
            },
        ),
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('abbrev', models.CharField(max_length=2, unique=True)),
                ('lake_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['abbrev'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('spc', models.CharField(max_length=3, unique=True)),
                ('abbrev', models.CharField(blank=True, max_length=5, null=True, verbose_name='US Abbreviation')),
                ('spc_nm', models.CharField(blank=True, max_length=50, null=True, verbose_name='Species Name')),
                ('spc_nmco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Official Common Name')),
                ('spc_nmsc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Scientific Name')),
                ('spc_lab', models.CharField(max_length=10)),
                ('spc_nmfam', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('royalty_flag', models.BooleanField(default=False)),
                ('quota_flag', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Species',
                'ordering': ['spc'],
            },
        ),
        migrations.CreateModel(
            name='ManagementUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=25)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('primary', models.BooleanField(db_index=True, default=False, verbose_name='Primary management unit type for this jurisdiciton.')),
                ('mu_type', models.CharField(choices=[('mu', 'Management Unit'), ('ltrz', 'Lake Trout Rehabilitation Zone'), ('bltrz', 'Buffered Lake Trout Rehabilitation Zone'), ('qma', 'Quota Management Area'), ('aa', 'Assessment Area'), ('area', 'Area'), ('subarea', 'Assessment Area'), ('stat_dist', 'Statistical District'), ('moe', 'MOE Block'), ('basin', 'Basin'), ('naz', 'Nearshore Assessment Zone'), ('grid10', '10-Minute Grid'), ('region', 'Region')], default='mu', max_length=10)),
                ('grids', models.ManyToManyField(to='common.Grid5')),
                ('lake', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Lake')),
            ],
            options={
                'ordering': ['lake__abbrev', 'mu_type', 'label'],
            },
        ),
        migrations.AddField(
            model_name='grid5',
            name='lake',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Lake'),
        ),
    ]
