# Generated by Django 2.2.12 on 2020-04-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200414_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid5',
            name='grid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='lake',
            name='abbrev',
            field=models.CharField(db_index=True, max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='managementunit',
            name='label',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='species',
            name='spc',
            field=models.CharField(db_index=True, max_length=3, unique=True),
        ),
    ]
