# Generated by Django 3.2.12 on 2022-09-19 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_add_id_autofield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementUnitType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('abbrev', models.CharField(db_index=True, max_length=5)),
                ('label', models.CharField(db_index=True, max_length=25)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='managementunit',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='managementunit',
            name='primary',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Primary management unit type for this lake.'),
        ),
        migrations.CreateModel(
            name='LakeManagementUnitType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('primary', models.BooleanField(db_index=True, default=False, verbose_name='Primary management unit type for this lake.')),
                ('lake', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.lake')),
                ('management_unit_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.managementunittype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lakemanagementunittype',
            constraint=models.UniqueConstraint(condition=models.Q(('primary', True)), fields=('lake',), name='unique_lake_manunit_primary'),
        ),
    ]
