# Generated by Django 3.2.12 on 2022-09-19 19:30
# Generated by Django 3.2.12 on 2022-09-19 18:53

from django.db import migrations
from django.template.defaultfilters import slugify


def fill_lake_management_unit_type(apps, schema_editor):
    ManagementUnit = apps.get_model("common", "ManagementUnit")
    ManagementUnitType = apps.get_model("common", "ManagementUnitType")
    LakeManagementUnitType = apps.get_model("common", "LakeManagementUnitType")
    Lake = apps.get_model("common", "Lake")

    for manunit in ManagementUnit.objects.all():

        lake = manunit.lake

        # get or create our management unit types
        abbrev = manunit.mu_type.upper()
        label = (manunit.get_mu_type_display(),)
        mu_type, created = ManagementUnitType.objects.get_or_create(
            abbrev=abbrev, label=label, slug=slugify("{}-{}".format(label, abbrev))
        )
        mu_type.save()
        # get or create our lake management units
        lake_mu_type, created = LakeManagementUnitType.objects.get_or_create(
            lake=lake, management_unit_type=mu_type
        )
        lake_mu_type.primary = manunit.primary
        lake_mu_type.save()


def unfill_lake_management_unit_type(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0010_manunit_type_fk_to_manunit"),
    ]

    operations = [
        migrations.RunPython(
            fill_lake_management_unit_type, unfill_lake_management_unit_type
        ),
    ]
