# Generated by Django 3.2.12 on 2022-09-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_populate_manunit_type_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managementunit',
            options={'ordering': ['lake__abbrev', 'label']},
        ),
        migrations.RemoveField(
            model_name='managementunit',
            name='mu_type',
        ),
        migrations.RemoveField(
            model_name='managementunit',
            name='primary',
        ),
    ]
