# Generated by Django 3.2.12 on 2022-09-30 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_remove_primary_mu_type_from_manunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementunit',
            name='lake_management_unit_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.lakemanagementunittype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managementunittype',
            name='abbrev',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AddConstraint(
            model_name='lakemanagementunittype',
            constraint=models.UniqueConstraint(fields=('lake', 'management_unit_type'), name='unique_lake_manunit_type'),
        ),
    ]
