# Generated by Django 3.2.12 on 2022-10-03 14:33

from django.db import migrations
from django.utils.text import slugify


def populate_bottom(apps, schema_editor):

    BottomType = apps.get_model("common", "BottomType")

    options = [
        ("BO", "Boulder (>25 cm)"),
        ("BR", "Bedrock or Rock"),
        ("CL", "Clay"),
        ("DE", "Detritus"),
        ("GP", "Gravel/Pebble (0.2-8 cm)"),
        ("MA", "Marl"),
        ("MU", "Muck"),
        ("RC", "Rubble/Cobble (8-25 cm)"),
        ("SA", "Sand"),
        ("SI", "Silt"),
    ]
    for item in options:
        abbrev, label = item
        slug = slugify(f"{label}-{abbrev}")
        bottom_type, created = BottomType.all_objects.get_or_create(
            abbrev=abbrev, label=label, slug=slug
        )
        bottom_type.save()


def depopulate_bottom(apps, schema_editor):
    pass


def populate_cover(apps, schema_editor):
    pass

    CoverType = apps.get_model("common", "CoverType")

    options = [
        ("BO", "Boulder*"),
        ("CO", "Combination"),
        ("LT", "Log & Tree*"),
        ("MA", "Macrophytes*"),
        ("NC", "No Cover*"),
        ("OD", "Organic Debris"),
        ("OT", "Other*"),
        ("UB", "Undercut Bank"),
    ]

    for item in options:
        abbrev, label = item
        slug = slugify(f"{label}-{abbrev}")
        cover_type, created = CoverType.all_objects.get_or_create(
            abbrev=abbrev, label=label, slug=slug
        )
        cover_type.save()


def depopulate_cover(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0014_abstract_model_lookups_bottom_cover_types"),
    ]

    operations = [
        migrations.RunPython(populate_bottom, depopulate_bottom),
        migrations.RunPython(populate_cover, depopulate_cover),
    ]
