# Generated by Django 3.2.12 on 2022-10-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_abstract_model_lookups_bottom_cover_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('taxon', models.CharField(db_index=True, max_length=10, unique=True)),
                ('itiscode', models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, verbose_name='ITIS TSN')),
                ('taxon_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Scientific Name')),
                ('taxon_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Common Name')),
                ('taxonomic_rank', models.CharField(blank=True, choices=[('other', 'Other'), ('domain', 'Domain'), ('kingdom', 'Kingdom'), ('subkingdom', 'Subkingdom'), ('infrakingdom', 'Infrakingdom'), ('superphylum', 'Superphylum'), ('phylum', 'Phylum'), ('infraphylum', 'Infraphylum'), ('subphylum', 'Subphylum'), ('class', 'Class'), ('subclass', 'Subclass'), ('superclass', 'Superclass'), ('infraclass', 'Infraclass'), ('order', 'Order'), ('infraorder', 'Infraorder'), ('suborder', 'Suborder'), ('superorder', 'Superorder'), ('genus', 'Genus'), ('subgenus', 'Subgenus'), ('family', 'Family'), ('superfamily', 'Superfamily'), ('subfamily', 'Subfamily'), ('tribe', 'Tribe'), ('species', 'Species')], default='species', max_length=15, null=True)),
                ('vertinvert', models.CharField(choices=[('other', 'Other'), ('plant', 'Plant'), ('invertebrate', 'Invertebrate'), ('vertebrate', 'Vertebrate')], default='invertebrate', max_length=12)),
                ('omnr_provincial_code', models.CharField(blank=True, db_index=True, max_length=4, null=True, unique=True, verbose_name='HHFAU Code')),
            ],
            options={
                'ordering': ['taxon'],
            },
        ),
    ]
